# Setup
title:               feb0339
tagline:             'Miss You'
description:         'Miss UU'
url:                 https://feb0339.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Amelie Wang
  url:               https://feb0339.github.io
  email:             amelie_wyj@outlook.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
